[2022-12-26T00:00:03.861+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test scheduled__2022-12-25T00:00:00+00:00 [queued]>
[2022-12-26T00:00:03.878+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test scheduled__2022-12-25T00:00:00+00:00 [queued]>
[2022-12-26T00:00:03.883+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-26T00:00:03.888+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2022-12-26T00:00:03.890+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-26T00:00:03.914+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_test> on 2022-12-25 00:00:00+00:00
[2022-12-26T00:00:03.923+0000] {standard_task_runner.py:55} INFO - Started process 6940 to run task
[2022-12-26T00:00:03.938+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'final_project_dag', 'extract_test', 'scheduled__2022-12-25T00:00:00+00:00', '--job-id', '270', '--raw', '--subdir', 'DAGS_FOLDER/final_project_dag.py', '--cfg-path', '/tmp/tmplkrwkwx1']
[2022-12-26T00:00:03.942+0000] {standard_task_runner.py:83} INFO - Job 270: Subtask extract_test
[2022-12-26T00:00:04.006+0000] {task_command.py:389} INFO - Running <TaskInstance: final_project_dag.extract_test scheduled__2022-12-25T00:00:00+00:00 [running]> on host cc86156a81c5
[2022-12-26T00:00:04.078+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kelompok2
AIRFLOW_CTX_DAG_ID=final_project_dag
AIRFLOW_CTX_TASK_ID=extract_test
AIRFLOW_CTX_EXECUTION_DATE=2022-12-25T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-25T00:00:00+00:00
[2022-12-26T00:00:05.140+0000] {streaming.py:185} INFO - Stream connected
[2022-12-26T00:05:22.176+0000] {local_task_job.py:224} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2022-12-26T00:05:22.182+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 6940. PIDs of all processes in the group: [6940]
[2022-12-26T00:05:22.183+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 6940
[2022-12-26T00:05:22.185+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-12-26T00:05:22.189+0000] {streaming.py:203} ERROR - Stream encountered an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/tweepy/streaming.py", line 91, in _connect
    chunk_size=self.chunk_size
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 866, in iter_lines
    chunk_size=chunk_size, decode_unicode=decode_unicode
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/response.py", line 624, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/response.py", line 828, in read_chunked
    self._update_chunk_length()
  File "/home/airflow/.local/lib/python3.7/site-packages/urllib3/response.py", line 758, in _update_chunk_length
    line = self._fp.fp.readline()
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-12-26T00:05:22.198+0000] {streaming.py:193} INFO - Stream disconnected
[2022-12-26T00:05:22.236+0000] {logging_mixin.py:137} INFO -                tweet_id  ... source
80  1607165558298136577  ...   None
81  1607165558763683840  ...   None
82  1607165561833947140  ...   None
83  1607165572219043840  ...   None
84  1607165593701974016  ...   None

[5 rows x 5 columns]
[2022-12-26T00:05:22.239+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-26T00:05:22.252+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=final_project_dag, task_id=extract_test, execution_date=20221225T000000, start_date=20221226T000003, end_date=20221226T000522
[2022-12-26T00:05:22.318+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=6940, status='terminated', exitcode=0, started='00:00:03') (6940) terminated with exit code 0
