[2022-12-25T16:08:02.846+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-25T11:23:40.384770+00:00 [queued]>
[2022-12-25T16:08:02.859+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-25T11:23:40.384770+00:00 [queued]>
[2022-12-25T16:08:02.864+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-25T16:08:02.865+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 6
[2022-12-25T16:08:02.867+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-25T16:08:02.912+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_test> on 2022-12-25 11:23:40.384770+00:00
[2022-12-25T16:08:02.920+0000] {standard_task_runner.py:55} INFO - Started process 397 to run task
[2022-12-25T16:08:02.924+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'final_project_dag', 'extract_test', 'manual__2022-12-25T11:23:40.384770+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/final_project_dag.py', '--cfg-path', '/tmp/tmpij_ncqnb']
[2022-12-25T16:08:02.928+0000] {standard_task_runner.py:83} INFO - Job 248: Subtask extract_test
[2022-12-25T16:08:03.018+0000] {task_command.py:389} INFO - Running <TaskInstance: final_project_dag.extract_test manual__2022-12-25T11:23:40.384770+00:00 [running]> on host cc86156a81c5
[2022-12-25T16:08:03.103+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kelompok2
AIRFLOW_CTX_DAG_ID=final_project_dag
AIRFLOW_CTX_TASK_ID=extract_test
AIRFLOW_CTX_EXECUTION_DATE=2022-12-25T11:23:40.384770+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-25T11:23:40.384770+00:00
[2022-12-25T16:08:04.143+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T16:08:04.145+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T16:09:05.082+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T16:09:05.085+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T16:11:05.711+0000] {streaming.py:185} INFO - Stream connected
[2022-12-25T16:11:29.927+0000] {streaming.py:180} ERROR - Stream connection closed by Twitter
[2022-12-25T16:11:29.933+0000] {streaming.py:193} INFO - Stream disconnected
[2022-12-25T16:11:29.935+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-25T16:11:29.950+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=final_project_dag, task_id=extract_test, execution_date=20221225T112340, start_date=20221225T160802, end_date=20221225T161129
[2022-12-25T16:11:30.042+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-25T16:11:30.062+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
