[2022-12-25T11:23:57.987+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-25T11:23:40.384770+00:00 [queued]>
[2022-12-25T11:23:58.051+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-25T11:23:40.384770+00:00 [queued]>
[2022-12-25T11:23:58.059+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-25T11:23:58.063+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2022-12-25T11:23:58.066+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-25T11:23:58.145+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_test> on 2022-12-25 11:23:40.384770+00:00
[2022-12-25T11:23:58.191+0000] {standard_task_runner.py:55} INFO - Started process 3733 to run task
[2022-12-25T11:23:58.226+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'final_project_dag', 'extract_test', 'manual__2022-12-25T11:23:40.384770+00:00', '--job-id', '238', '--raw', '--subdir', 'DAGS_FOLDER/final_project_dag.py', '--cfg-path', '/tmp/tmp994g86yh']
[2022-12-25T11:23:58.235+0000] {standard_task_runner.py:83} INFO - Job 238: Subtask extract_test
[2022-12-25T11:23:58.589+0000] {task_command.py:389} INFO - Running <TaskInstance: final_project_dag.extract_test manual__2022-12-25T11:23:40.384770+00:00 [running]> on host cc86156a81c5
[2022-12-25T11:23:59.111+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kelompok2
AIRFLOW_CTX_DAG_ID=final_project_dag
AIRFLOW_CTX_TASK_ID=extract_test
AIRFLOW_CTX_EXECUTION_DATE=2022-12-25T11:23:40.384770+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-25T11:23:40.384770+00:00
[2022-12-25T11:24:00.195+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T11:24:00.219+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T11:25:00.652+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T11:25:00.656+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T11:27:01.083+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T11:27:01.091+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T11:31:01.470+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T11:31:01.476+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T11:36:42.655+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:36:42.686+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8681f410>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:37:03.734+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:37:03.743+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86613890>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:37:25.024+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:37:25.032+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86613b90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:37:46.552+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:37:46.557+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff867cf850>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:38:08.324+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:38:08.330+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff867cfc90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:38:30.382+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:38:30.387+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661a810>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:38:52.664+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:38:52.670+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661ad50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:39:15.219+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:39:15.226+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff866217d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:39:38.042+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:39:38.050+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86621f90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:40:01.111+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:40:02.902+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865a8790>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:40:26.206+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:40:26.213+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff867abc10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:40:49.771+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:40:49.779+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86621350>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:41:13.579+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:41:13.585+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86819f90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:41:37.631+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:41:37.638+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661a2d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:42:01.945+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:42:01.953+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661a6d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:42:26.513+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:42:26.522+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff866139d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:42:51.334+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:42:51.355+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff867baa10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:43:16.439+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:43:16.447+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8679fd10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:43:41.791+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:43:41.797+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff867baa10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:44:07.483+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:44:07.491+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86613a50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:44:33.329+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:44:33.336+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86819f90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:44:59.453+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:44:59.460+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661a990>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:45:25.767+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:45:25.772+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661a390>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:45:52.339+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:45:52.347+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86621590>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:46:19.147+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:46:19.153+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86621ad0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:46:46.193+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:46:46.207+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8c6a0dd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:47:13.489+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:47:13.497+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8d860d90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:47:41.051+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:47:41.057+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865a8e50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:48:08.850+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:48:08.856+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86619650>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:48:36.904+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:48:36.911+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865a8bd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:49:05.227+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:49:05.233+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8d33ac90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:49:33.783+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:49:33.790+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8d77f9d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:50:02.576+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:50:02.585+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86621cd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:50:31.637+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:50:31.666+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86621710>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:51:00.982+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:51:00.990+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661af10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:51:30.569+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:51:30.575+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661a2d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:52:00.408+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:52:00.427+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86613950>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:52:30.491+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:52:30.517+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff866137d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:53:00.827+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:53:00.836+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86ac2210>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:53:31.394+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:53:31.402+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8679fd10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:54:02.215+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:54:02.226+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86619ed0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:54:33.307+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:54:33.319+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865ae8d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:55:04.623+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:55:04.631+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86619d90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:55:36.214+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:55:36.223+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86619fd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:56:08.083+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:56:08.091+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86ac21d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:56:40.161+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:56:40.169+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86613a10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:57:12.477+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:57:12.486+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661a2d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:57:45.025+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:57:45.038+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661af50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:58:17.848+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:58:17.856+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86621e50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:58:50.918+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:58:50.929+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86621c10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:59:22.635+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T11:59:22.643+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T12:04:46.350+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T12:04:46.371+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T12:10:06.851+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T12:10:06.855+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T12:15:27.459+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T12:15:27.466+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T12:20:48.052+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T12:20:48.056+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T12:26:08.594+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T12:26:08.599+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T12:31:29.127+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T12:31:29.131+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T12:36:52.714+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T12:36:52.724+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T12:42:13.245+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T12:42:13.251+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T12:47:33.678+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T12:47:33.685+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T12:52:54.220+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T12:52:54.226+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T12:58:14.739+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T12:58:14.748+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T13:03:35.266+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T13:03:35.271+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T13:08:55.782+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T13:08:55.790+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T13:14:16.294+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T13:14:16.301+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T13:19:57.363+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:19:57.370+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff867bad90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:20:30.916+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:20:30.923+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865a85d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:21:04.735+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:21:04.744+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865aeb50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:21:38.795+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:21:38.817+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b1390>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:22:13.144+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:22:13.150+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8c6a0f10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:22:47.720+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:22:47.730+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86abf7d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:23:22.545+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:23:22.553+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86621890>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:23:57.616+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:23:57.626+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661af50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:24:32.931+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:24:32.937+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661ae90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:25:08.501+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:25:08.511+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661a9d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:25:44.348+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:25:44.357+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86613dd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:26:20.405+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:26:20.411+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86ac2910>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:26:56.765+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:26:56.789+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86ac2410>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:27:33.367+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:27:33.373+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86619a90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:28:10.192+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:28:10.199+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865ae7d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:28:47.275+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:28:47.283+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865aec10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:29:24.338+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:29:24.347+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b1e50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:30:01.403+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:30:01.412+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b1850>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:30:38.482+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:30:38.506+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865ae2d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:31:15.556+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:31:15.563+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86619a50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:31:52.700+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:31:52.706+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffffa0a692d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:32:29.770+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:32:29.777+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86b80590>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:33:06.837+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:33:06.850+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86613c10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:33:43.914+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:33:43.929+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86613c90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:34:21.009+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:34:21.015+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661a5d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:34:58.106+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:34:58.113+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661a650>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:35:35.179+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:35:35.186+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff866218d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:36:12.245+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:36:12.255+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86abfb10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:36:49.319+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:36:49.326+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865a80d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:37:26.379+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:37:26.386+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b3950>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:38:03.445+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:38:03.452+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865a8190>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:38:40.498+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:38:40.505+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86621410>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:39:17.617+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:39:17.624+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86621350>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:39:54.678+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:39:54.686+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661ac50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:40:31.739+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:40:31.747+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661a750>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:41:08.801+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:41:08.816+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86613790>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:41:45.872+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:41:45.882+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86613e50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:42:22.975+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:42:22.989+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86ac2290>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:43:00.074+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:43:00.092+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86619450>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:43:37.169+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:43:37.176+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865ae590>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:44:14.265+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:44:14.279+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865ae510>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:44:51.329+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:44:51.336+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b3bd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:45:28.401+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:45:28.420+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b7450>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:46:05.477+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:46:05.491+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b3090>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:46:42.562+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:46:42.568+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865ae950>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:47:19.632+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:47:19.639+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865aeb90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:47:56.725+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:47:56.735+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86619f90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:48:33.856+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:48:33.866+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86ac2350>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:49:10.978+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:49:10.991+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86ac2590>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:49:48.070+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:49:48.080+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff866136d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:50:25.156+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:50:25.163+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661a8d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:51:02.237+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:51:02.244+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661abd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:51:39.348+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:51:39.358+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86621c10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:52:16.430+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:52:16.444+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86621210>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:52:53.545+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:52:53.558+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8c6a0fd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:53:30.624+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:53:30.640+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b7f10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:54:07.701+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:54:07.708+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff9b71bb50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:54:44.784+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:54:44.799+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865a8f50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:55:21.913+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:55:21.922+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff866211d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:55:58.995+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:55:59.002+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661a210>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:56:36.074+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:56:36.091+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661a9d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:57:13.169+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:57:13.183+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86613990>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:57:50.250+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:57:50.269+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff867ba490>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:58:27.366+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:58:27.388+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86ac2150>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:59:04.460+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:59:04.467+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86619b10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:59:41.530+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:59:41.538+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865ae590>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:00:18.620+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:00:18.627+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b16d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:00:55.700+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:00:55.708+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b3290>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:01:32.784+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:01:32.804+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b9a10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:02:09.857+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:02:09.873+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b3bd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:02:46.971+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:02:46.981+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865aea90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:03:24.041+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:03:24.049+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86619f90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:04:01.115+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:04:01.123+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865aeed0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:04:38.200+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:04:38.207+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86ac24d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:05:15.298+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:05:15.305+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86613d10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:05:52.382+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:05:52.405+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661a950>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:06:29.467+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:06:29.476+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661aad0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:07:06.537+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:07:06.545+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86621810>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:07:43.616+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:07:43.626+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff866214d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:08:20.701+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:08:20.716+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865a8bd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:08:57.800+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:08:57.808+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b9c90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:09:34.906+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:09:34.920+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865c04d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:10:11.997+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:10:12.005+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b9190>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:10:49.085+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:10:49.093+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b91d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:11:26.214+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:11:26.233+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86621950>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:12:03.328+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:12:03.342+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86621ed0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:12:40.425+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:12:40.434+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661ad10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:13:17.520+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:13:17.526+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661a050>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:13:55.116+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:13:55.244+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661a110>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:14:32.382+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:14:32.454+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86ac2bd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:15:09.532+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:15:09.539+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86619e90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:15:46.592+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:15:46.603+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865aea90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:16:23.768+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:16:23.782+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b1750>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:17:00.847+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:17:00.856+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b32d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:17:37.925+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:17:37.935+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865c0d50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:18:14.999+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:18:15.005+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865c0910>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:18:52.046+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:18:52.052+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffffa0a692d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:19:29.123+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:19:29.130+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865ae990>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:20:06.232+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:20:06.241+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86b80710>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:20:43.315+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:20:43.328+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86ac2ad0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:21:20.434+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:21:20.445+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86613910>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:21:57.520+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:21:57.529+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86613850>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:22:34.600+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:22:34.606+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661a450>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:23:11.664+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:23:11.671+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86621610>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:23:48.736+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:23:48.744+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86abfb10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:24:25.824+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:24:25.846+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b7d50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:25:02.883+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:25:02.889+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b9410>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:25:39.998+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:25:40.004+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865c3ad0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:26:17.067+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:26:17.075+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86abf750>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:26:54.125+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:26:54.131+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86621e10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:27:31.194+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:27:31.202+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661a190>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:28:08.275+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:28:08.291+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661a610>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:28:45.392+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:28:45.435+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86ac2910>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:29:22.655+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:29:22.666+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86ac24d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:29:59.739+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:29:59.745+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865c0bd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:30:36.983+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:30:37.039+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865c0550>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:31:14.267+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:31:14.343+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86613fd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:31:51.875+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:31:51.953+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b9590>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:32:38.090+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:32:38.120+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b7810>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:33:16.054+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:33:16.811+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b7710>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:34:00.709+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:34:01.266+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b3d10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:34:42.176+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:34:43.061+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b73d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:35:20.716+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:35:20.840+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b7290>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:35:58.565+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:35:59.011+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865b9550>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:36:36.999+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:36:37.232+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86613990>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:36:46.914+0000] {local_task_job.py:159} INFO - Task exited with return code Negsignal.SIGKILL
[2022-12-25T14:36:48.637+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
