[2022-12-25T04:45:20.589+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: test_etl_deps.etl_test manual__2022-12-25T04:39:14.458436+00:00 [queued]>
[2022-12-25T04:45:20.599+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: test_etl_deps.etl_test manual__2022-12-25T04:39:14.458436+00:00 [queued]>
[2022-12-25T04:45:20.601+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-25T04:45:20.603+0000] {taskinstance.py:1284} INFO - Starting attempt 4 of 6
[2022-12-25T04:45:20.604+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-25T04:45:20.624+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): etl_test> on 2022-12-25 04:39:14.458436+00:00
[2022-12-25T04:45:20.632+0000] {standard_task_runner.py:55} INFO - Started process 3293 to run task
[2022-12-25T04:45:20.638+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'test_etl_deps', 'etl_test', 'manual__2022-12-25T04:39:14.458436+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/test_etl_deps.py', '--cfg-path', '/tmp/tmpnr9spui1']
[2022-12-25T04:45:20.640+0000] {standard_task_runner.py:83} INFO - Job 165: Subtask etl_test
[2022-12-25T04:45:20.708+0000] {task_command.py:389} INFO - Running <TaskInstance: test_etl_deps.etl_test manual__2022-12-25T04:39:14.458436+00:00 [running]> on host 176142c05a95
[2022-12-25T04:45:20.779+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kelompok2
AIRFLOW_CTX_DAG_ID=test_etl_deps
AIRFLOW_CTX_TASK_ID=etl_test
AIRFLOW_CTX_EXECUTION_DATE=2022-12-25T04:39:14.458436+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-25T04:39:14.458436+00:00
[2022-12-25T04:45:20.783+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2022-12-25T04:45:20.785+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'tree']
[2022-12-25T04:45:20.798+0000] {subprocess.py:86} INFO - Output:
[2022-12-25T04:45:20.802+0000] {subprocess.py:93} INFO - /bin/bash: line 1: tree: command not found
[2022-12-25T04:45:20.804+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2022-12-25T04:45:20.817+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-12-25T04:45:20.823+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=test_etl_deps, task_id=etl_test, execution_date=20221225T043914, start_date=20221225T044520, end_date=20221225T044520
[2022-12-25T04:45:20.839+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 165 for task etl_test (Bash command failed. The command returned a non-zero exit code 127.; 3293)
[2022-12-25T04:45:20.894+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-25T04:45:20.922+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
