[2022-12-25T11:12:22.782+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-25T11:12:12.545613+00:00 [queued]>
[2022-12-25T11:12:22.802+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-25T11:12:12.545613+00:00 [queued]>
[2022-12-25T11:12:22.804+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-25T11:12:22.807+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2022-12-25T11:12:22.812+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-25T11:12:22.887+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_test> on 2022-12-25 11:12:12.545613+00:00
[2022-12-25T11:12:22.908+0000] {standard_task_runner.py:55} INFO - Started process 3091 to run task
[2022-12-25T11:12:22.921+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'final_project_dag', 'extract_test', 'manual__2022-12-25T11:12:12.545613+00:00', '--job-id', '236', '--raw', '--subdir', 'DAGS_FOLDER/final_project_dag.py', '--cfg-path', '/tmp/tmp7d03h_qi']
[2022-12-25T11:12:22.928+0000] {standard_task_runner.py:83} INFO - Job 236: Subtask extract_test
[2022-12-25T11:12:23.065+0000] {task_command.py:389} INFO - Running <TaskInstance: final_project_dag.extract_test manual__2022-12-25T11:12:12.545613+00:00 [running]> on host cc86156a81c5
[2022-12-25T11:12:23.220+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kelompok2
AIRFLOW_CTX_DAG_ID=final_project_dag
AIRFLOW_CTX_TASK_ID=extract_test
AIRFLOW_CTX_EXECUTION_DATE=2022-12-25T11:12:12.545613+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-25T11:12:12.545613+00:00
[2022-12-25T11:12:24.267+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T11:12:24.277+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T11:13:24.737+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T11:13:24.750+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T11:15:25.186+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T11:15:25.192+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T11:19:25.697+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T11:19:25.708+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T11:24:46.418+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T11:24:46.428+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T11:30:07.044+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T11:30:07.049+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T11:35:48.221+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:35:48.270+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff867dacd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:36:09.315+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:36:09.329+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865c9c90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:36:30.638+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:36:30.655+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d1490>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:36:52.210+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:36:52.219+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d1c50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:37:14.022+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:37:14.027+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d5450>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:37:36.073+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:37:36.079+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d5c10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:37:58.375+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:37:58.381+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d9410>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:38:20.941+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:38:20.948+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d9bd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:38:43.748+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:38:43.756+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e13d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:39:06.841+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:39:06.871+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e1b90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:39:30.164+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:39:30.179+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e1190>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:39:53.728+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:39:53.738+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d9750>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:40:17.544+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:40:17.552+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d9310>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:40:41.615+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:40:41.622+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d5dd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:41:05.910+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:41:05.917+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d5150>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:41:30.458+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:41:30.465+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d1e10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:41:55.284+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:41:55.290+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d1350>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:42:20.347+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:42:20.354+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865c9b50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:42:45.637+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:42:45.643+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8676f490>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:43:11.199+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:43:11.205+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d25d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:43:37.004+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:43:37.011+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d2d90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:44:03.067+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:44:03.074+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8656e590>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:44:29.373+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:44:29.380+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d28d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:44:55.917+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:44:55.924+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d2750>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:45:22.725+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:45:22.732+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8676fd50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:45:49.782+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:45:49.793+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865c9e10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:46:17.102+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:46:17.108+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d1a50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:46:44.665+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:46:44.672+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d1cd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:47:12.459+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:47:12.466+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d5290>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:47:40.522+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:47:40.529+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d5b50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:48:08.838+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:48:08.847+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d9210>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:48:37.396+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:48:37.404+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d9fd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:49:06.206+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:49:06.215+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e10d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:49:35.263+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:49:35.270+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8656ec90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:50:04.580+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:50:04.591+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86573810>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:50:34.158+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:50:34.167+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8656edd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:51:03.974+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:51:03.981+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e1150>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:51:34.042+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:51:34.049+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d95d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:52:04.382+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:52:04.394+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d9a50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:52:34.969+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:52:34.978+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d5750>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:53:05.785+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:53:05.792+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d5a10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:53:36.859+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:53:36.867+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d10d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:54:08.156+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:54:08.163+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d1ad0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:54:39.726+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:54:39.735+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff867599d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:55:11.534+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:55:11.541+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff867cff50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:55:43.587+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:55:43.596+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d2850>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:56:15.911+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:56:15.920+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86573b10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:56:48.501+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:56:48.512+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86579310>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:57:21.308+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:57:21.314+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d2dd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:57:54.390+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:57:54.399+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865d2650>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:58:27.707+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:58:27.714+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8676fa50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:59:01.280+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:59:01.291+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff867dad10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:59:16.663+0000] {streaming.py:185} INFO - Stream connected
[2022-12-25T11:59:54.403+0000] {streaming.py:180} ERROR - Stream connection closed by Twitter
[2022-12-25T11:59:54.423+0000] {streaming.py:193} INFO - Stream disconnected
[2022-12-25T11:59:54.430+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-25T11:59:54.527+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=final_project_dag, task_id=extract_test, execution_date=20221225T111212, start_date=20221225T111222, end_date=20221225T115954
[2022-12-25T11:59:54.777+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-25T11:59:54.867+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
