[2022-12-25T11:11:19.759+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-25T11:06:58.079596+00:00 [queued]>
[2022-12-25T11:11:19.988+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-25T11:06:58.079596+00:00 [queued]>
[2022-12-25T11:11:20.001+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-25T11:11:20.005+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 6
[2022-12-25T11:11:20.008+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-25T11:11:20.090+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_test> on 2022-12-25 11:06:58.079596+00:00
[2022-12-25T11:11:20.136+0000] {standard_task_runner.py:55} INFO - Started process 3035 to run task
[2022-12-25T11:11:20.249+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'final_project_dag', 'extract_test', 'manual__2022-12-25T11:06:58.079596+00:00', '--job-id', '234', '--raw', '--subdir', 'DAGS_FOLDER/final_project_dag.py', '--cfg-path', '/tmp/tmp1n2ynuyo']
[2022-12-25T11:11:20.329+0000] {standard_task_runner.py:83} INFO - Job 234: Subtask extract_test
[2022-12-25T11:11:20.770+0000] {task_command.py:389} INFO - Running <TaskInstance: final_project_dag.extract_test manual__2022-12-25T11:06:58.079596+00:00 [running]> on host cc86156a81c5
[2022-12-25T11:11:21.188+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kelompok2
AIRFLOW_CTX_DAG_ID=final_project_dag
AIRFLOW_CTX_TASK_ID=extract_test
AIRFLOW_CTX_EXECUTION_DATE=2022-12-25T11:06:58.079596+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-25T11:06:58.079596+00:00
[2022-12-25T11:11:22.398+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T11:11:22.420+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T11:12:22.823+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T11:12:22.840+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T11:14:23.249+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T11:14:23.254+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T11:18:23.585+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T11:18:23.589+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T11:23:44.790+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T11:23:44.824+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T11:29:05.477+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T11:29:05.483+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T11:34:49.664+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:34:49.686+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86be2310>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:35:10.725+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:35:10.730+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8665e3d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:35:32.020+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:35:32.033+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8665eb90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:35:53.577+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:35:53.586+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e3390>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:36:15.380+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:36:15.389+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e3b50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:36:37.446+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:36:37.451+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e7350>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:36:59.727+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:36:59.733+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e7b10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:37:22.297+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:37:22.305+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865ec310>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:37:45.109+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:37:45.120+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865ecad0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:38:08.164+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:38:08.188+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f22d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:38:31.487+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:38:31.493+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865eca10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:38:55.030+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:38:55.037+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865ec410>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:39:18.840+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:39:18.848+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e7710>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:39:42.885+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:39:42.891+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e7090>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:40:07.194+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:40:07.203+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e30d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:40:31.759+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:40:31.770+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e3c10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:40:56.569+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:40:56.587+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8665e550>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:41:21.659+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:41:21.676+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86803cd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:41:46.994+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:41:47.003+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff867fa390>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:42:12.580+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:42:12.593+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f2cd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:42:38.397+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:42:38.406+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865fb4d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:43:04.467+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:43:04.475+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865fbc90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:43:30.776+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:43:30.784+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f2750>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:43:57.340+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:43:57.347+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f2450>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:44:24.166+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:44:24.173+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86be2d10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:44:51.247+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:44:51.255+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8665ecd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:45:18.575+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:45:18.590+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8665ed90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:45:46.166+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:45:46.174+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e3a50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:46:13.960+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:46:13.968+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e7f90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:46:42.007+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:46:42.014+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e78d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:47:10.325+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:47:10.332+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865ec1d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:47:38.933+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:47:38.943+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865ecc90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:48:07.720+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:48:07.728+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865fb050>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:48:36.775+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:48:36.781+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f9750>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:49:06.107+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:49:06.115+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f9f10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:49:35.649+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:49:35.658+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865fb650>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:50:05.482+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:50:05.489+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865eca10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:50:35.562+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:50:35.576+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e7cd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:51:05.937+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:51:05.958+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e7c10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:51:36.499+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:51:36.510+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e39d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:52:07.336+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:52:07.345+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e3210>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:52:38.427+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:52:38.438+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8665e510>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:53:09.742+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:53:09.750+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8665e810>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:53:41.332+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:53:41.349+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e7d50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:54:13.162+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:54:13.170+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f2650>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:54:45.234+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:54:45.244+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f9290>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:55:17.549+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:55:17.567+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f9050>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:55:50.128+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:55:50.138+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86605a10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:56:22.962+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:56:22.969+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f2d10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:56:56.019+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:56:56.029+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f2b90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:57:29.341+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:57:29.349+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86be2150>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:58:02.915+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:58:02.934+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8665e190>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:58:36.754+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:58:36.765+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e3b90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:59:10.820+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T11:59:10.827+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e3dd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T11:59:24.579+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T11:59:24.586+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T12:04:46.347+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T12:04:46.366+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T12:10:06.842+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T12:10:06.847+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T12:15:27.459+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T12:15:27.466+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T12:20:48.034+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T12:20:48.038+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T12:26:08.594+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T12:26:08.599+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T12:31:29.125+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T12:31:29.131+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T12:36:52.722+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T12:36:52.733+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T12:42:13.249+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T12:42:13.254+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T12:47:33.762+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T12:47:33.775+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T12:52:54.271+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T12:52:54.276+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T12:58:14.803+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T12:58:14.809+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T13:03:35.326+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T13:03:35.331+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T13:08:55.848+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T13:08:55.853+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T13:14:16.394+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-25T13:14:16.399+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-25T13:19:57.535+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:19:57.541+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e7a90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:20:32.090+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:20:32.097+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865ec950>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:21:06.890+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:21:06.896+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f9410>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:21:41.959+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:21:41.967+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f9ed0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:22:17.279+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:22:17.287+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865fbad0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:22:52.892+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:22:52.898+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86605d10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:23:28.720+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:23:28.728+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8660c4d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:24:04.770+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:24:04.777+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86605190>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:24:41.080+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:24:41.088+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865fb5d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:25:17.691+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:25:17.698+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f9790>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:25:54.547+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:25:54.569+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f9a50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:26:31.640+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:26:31.654+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e7410>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:27:08.715+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:27:08.726+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e3d10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:27:45.798+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:27:45.816+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e3fd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:28:22.925+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:28:22.932+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8665efd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:28:59.975+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:28:59.983+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff867faf10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:29:37.077+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:29:37.086+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86be2650>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:30:14.153+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:30:14.162+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f2d50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:30:51.223+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:30:51.241+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f2d90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:31:28.324+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:31:28.334+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8660cd50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:32:05.385+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:32:05.393+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8660c350>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:32:42.453+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:32:42.459+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8660c6d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:33:19.522+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:33:19.542+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86be2190>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:33:56.589+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:33:56.596+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86be2f10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:34:33.674+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:34:33.681+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8665eb10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:35:10.767+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:35:10.780+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e3450>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:35:47.828+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:35:47.834+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e30d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:36:24.901+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:36:24.908+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e3ad0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:37:01.961+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:37:01.968+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f9f10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:37:39.031+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:37:39.038+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f9d90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:38:16.110+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:38:16.133+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865fb190>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:38:53.189+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:38:53.199+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86605e50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:39:30.269+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:39:30.277+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8660aad0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:40:07.346+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:40:07.354+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86605dd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:40:44.410+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:40:44.418+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865fb650>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:41:21.461+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:41:21.470+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f9290>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:41:58.540+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:41:58.549+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865ec650>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:42:35.611+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:42:35.626+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e7d90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:43:12.764+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:43:12.773+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e3d10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:43:49.823+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:43:49.835+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8665e790>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:44:26.917+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:44:26.925+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8665e810>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:45:04.004+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:45:04.014+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86be2b50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:45:41.086+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:45:41.093+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86be2090>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:46:18.176+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:46:18.182+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f2550>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:46:55.243+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:46:55.249+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8660ad50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:47:32.343+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:47:32.356+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff866145d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:48:09.447+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:48:09.458+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8660ae10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:48:46.577+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:48:46.592+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f2610>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:49:23.660+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:49:23.667+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f2710>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:50:00.701+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:50:00.709+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f2fd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:50:37.773+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:50:37.794+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8665e690>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:51:14.874+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:51:14.881+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8665ed90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:51:51.966+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:51:51.973+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e3f50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:52:29.039+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:52:29.047+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e7e50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:53:06.122+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:53:06.129+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865eca90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:53:43.163+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:53:43.169+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f9810>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:54:20.268+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:54:20.277+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865fb350>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:54:57.350+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:54:57.358+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86605c50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:55:34.438+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:55:34.443+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86614e90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:56:11.495+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:56:11.509+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff866149d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:56:48.571+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:56:48.579+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865fbe90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:57:25.639+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:57:25.652+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f9590>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:58:02.723+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:58:02.732+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865ec210>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:58:39.818+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:58:39.828+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e7b90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:59:16.924+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:59:16.933+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e3a90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T13:59:53.978+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T13:59:53.986+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8665ec10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:00:31.022+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:00:31.029+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8665e5d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:01:08.070+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:01:08.077+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86be2c90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:01:45.165+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:01:45.171+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f2750>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:02:22.236+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:02:22.242+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8660c910>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:02:59.311+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:02:59.322+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8660ae50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:03:36.442+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:03:36.450+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86617b90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:04:13.549+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:04:13.574+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8660a390>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:04:50.644+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:04:50.650+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f2550>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:05:27.709+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:05:27.716+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86be2dd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:06:04.823+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:06:04.845+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff867fadd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:06:41.893+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:06:41.901+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8665e950>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:07:18.951+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:07:18.960+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e3250>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:07:56.068+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:07:56.090+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e3450>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:08:33.165+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:08:33.173+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e7850>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:09:10.259+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:09:10.266+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f9dd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:09:47.360+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:09:47.376+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865fb610>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:10:24.453+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:10:24.463+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86605190>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:11:01.549+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:11:01.556+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff866172d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:11:38.890+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:11:38.914+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661b690>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:12:15.969+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:12:15.988+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86617490>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:12:53.118+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:12:53.133+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86605c90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:13:30.194+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:13:30.206+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f9590>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:14:07.303+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:14:07.315+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f9210>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:14:44.440+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:14:44.470+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e75d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:15:21.567+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:15:21.575+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e3250>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:15:58.656+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:15:58.707+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e3950>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:16:35.764+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:16:35.781+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8665e5d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:17:12.841+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:17:12.848+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86be2ed0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:17:49.909+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:17:49.916+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865f2d50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:18:26.997+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:18:27.003+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8660c890>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:19:04.046+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:19:04.053+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8660cad0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:19:41.117+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:19:41.131+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661bf50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:20:18.203+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:20:18.229+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86be2b50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:20:55.308+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:20:55.325+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8665eb90>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:21:32.418+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:21:32.434+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8665ec50>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:22:09.511+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:22:09.519+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e7350>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:22:46.585+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:22:46.597+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8661b290>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:23:23.641+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:23:23.647+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86617610>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:24:00.709+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:24:00.718+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86617150>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:24:37.794+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:24:37.805+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86614c10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:25:14.880+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:25:14.889+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff86614710>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:25:51.941+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:25:51.951+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e37d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:26:29.023+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:26:29.039+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8660a4d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:27:06.109+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:27:06.116+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8660a490>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:27:43.172+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:27:44.540+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8660ccd0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:28:21.681+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:28:21.936+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff868690d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:28:59.224+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:28:59.244+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8660a710>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:29:36.368+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:29:36.376+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8660af10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:30:13.524+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:30:13.580+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e3b10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:30:50.712+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:30:50.728+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e3510>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:31:28.527+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:31:28.603+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e70d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:32:07.102+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:32:09.774+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8665eb10>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:32:53.156+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:32:53.256+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff8665e390>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:33:31.038+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:33:31.780+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e7690>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:34:09.259+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:34:10.503+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e7210>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:34:49.795+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:34:54.522+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffff865e31d0>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:35:33.523+0000] {streaming.py:189} ERROR - Stream connection has errored or timed out
[2022-12-25T14:35:33.878+0000] {streaming.py:146} ERROR - Connection error: requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /2/tweets/search/stream?tweet.fields=author_id%2Ccreated_at%2Csource (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xffffa0da6050>, 'Connection to api.twitter.com timed out. (connect timeout=21)'))
[2022-12-25T14:35:52.700+0000] {local_task_job.py:159} INFO - Task exited with return code Negsignal.SIGKILL
[2022-12-25T14:36:02.836+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
