[2022-12-26T02:38:35.017+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-26T02:37:32.557300+00:00 [queued]>
[2022-12-26T02:38:35.329+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-26T02:37:32.557300+00:00 [queued]>
[2022-12-26T02:38:35.344+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-26T02:38:35.350+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2022-12-26T02:38:35.360+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-26T02:38:35.634+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_test> on 2022-12-26 02:37:32.557300+00:00
[2022-12-26T02:38:35.920+0000] {standard_task_runner.py:55} INFO - Started process 599 to run task
[2022-12-26T02:38:36.105+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'final_project_dag', 'extract_test', 'manual__2022-12-26T02:37:32.557300+00:00', '--job-id', '285', '--raw', '--subdir', 'DAGS_FOLDER/final_project_dag.py', '--cfg-path', '/tmp/tmpetjk4kkd']
[2022-12-26T02:38:36.189+0000] {standard_task_runner.py:83} INFO - Job 285: Subtask extract_test
[2022-12-26T02:38:37.182+0000] {task_command.py:389} INFO - Running <TaskInstance: final_project_dag.extract_test manual__2022-12-26T02:37:32.557300+00:00 [running]> on host ad7e32675cf9
[2022-12-26T02:38:38.166+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kelompok2
AIRFLOW_CTX_DAG_ID=final_project_dag
AIRFLOW_CTX_TASK_ID=extract_test
AIRFLOW_CTX_EXECUTION_DATE=2022-12-26T02:37:32.557300+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-26T02:37:32.557300+00:00
[2022-12-26T02:38:40.410+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-26T02:38:40.505+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-26T02:39:41.256+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-26T02:39:41.286+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-26T02:41:42.692+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-26T02:41:43.011+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-26T02:45:49.786+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-26T02:45:50.640+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-26T02:47:31.508+0000] {local_task_job.py:159} INFO - Task exited with return code Negsignal.SIGKILL
[2022-12-26T02:47:52.468+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
